sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
env:
  - DJANGO=1.9
  - DJANGO=master
install:
  - pip install tox coveralls
script:
  - tox -e py${TRAVIS_PYTHON_VERSION//[.]/}-$DJANGO
after_success:
  - coveralls